http:
  routers:
    traefik:
      entrypoints: "http,https"
      rule: "Host(`traefik.localhost`)"
      service: "api@internal"
      tls: true

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
