services:
  php74:
    image: php:7.4-fpm
    container_name: php-fpm74
    restart: unless-stopped
    volumes:
      - ../PHP:/var/www/html  # Montre tes sous-dossiers ici
    networks:
      - web

  php82:
    image: php:8.2-fpm
    container_name: php-fpm82
    restart: unless-stopped
    volumes:
      - ../PHP:/var/www/html  # Montre tes sous-dossiers ici
    networks:
      - web


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../PHP:/var/www/html  # Même volume partagé avec PHP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=HostRegexp(`.*.devphp.*.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - web


networks:
  web:
    external: true
